#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/docs/agent/REPO_MAP.md}"
if command -v mktemp >/dev/null 2>&1; then
  TMP="$(mktemp)"
else
  echo "mktemp not found; please install coreutils or provide mktemp in PATH" >&2
  exit 1
fi
trap '[[ -n "${TMP:-}" ]] && rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF_MAP
# Repo Map

This file is generated by \`scripts/refresh_repo_map.sh\`. Do not edit manually.

## Top-Level Layout

- \`crates/uc-cli\`: CLI, daemon, native compile path, cache/session restore, benchmarks integration.
- \`crates/uc-core\`: artifact and session primitives shared by the CLI.
- \`benchmarks/\`: fixtures, scripts, gates, baselines, and result outputs.
- \`docs/\`: architecture, roadmap, benchmark plan, research, and agent handoff docs.
- \`scripts/\`: bootstrap and validation helpers.
- \`third_party/cairo-lang-filesystem\`: local Cairo filesystem patch surface for keyed invalidation.

## Bootstrap Files

- \`AGENTS.md\`
- \`.codex/START_HERE.md\`
- \`docs/agent/PR_BOT_POLICY.md\`
- \`docs/agent/AGENT_FIRST_COMPILER.md\`
- \`docs/agent/AGENT_DIAGNOSTICS.md\`
- \`docs/agent/AGENT_QUICKSTART.md\`
- \`docs/agent/HUMAN_QUICKSTART.md\`
- \`docs/PROJECT_MODEL_STRATEGY.md\`
- \`docs/agent/schemas/\`
- \`.coderabbit.yaml\`
- \`.pr_agent.toml\`
- \`best_practices.md\`
- \`pr_compliance_checklist.yaml\`
- \`scripts/install_git_hooks.sh\`
- \`scripts/local_ci_gate.sh\`
- \`.githooks/pre-push\`

## Key Commands

- \`make bootstrap\`
- \`make install-hooks\`
- \`make doctor\`
- \`make local-ci\`
- \`make agent-map\`
- \`make agent-validate\`
- \`make validate-local-ci\`
- \`make validate-fast\`
- \`make validate-native\`
- \`uc agent eval --manifest-path /abs/path/to/Scarb.toml\`
- \`uc project inspect --manifest-path /abs/path/to/Scarb.toml --format json\`
- \`uc agent safe-action build-helper-lane --lane 2.14\`
- \`uc build --engine uc --daemon-mode off --manifest-path /abs/path/to/Scarb.toml --record-failure /abs/path/to/uc-failure.json\`
- \`uc replay /abs/path/to/uc-failure.json\`
- \`uc mcp serve\`
- \`make benchmark-strict-smoke\`
- \`make benchmark-strict-research\`
- \`benchmarks/scripts/run_real_repo_benchmarks.sh\`
- \`scripts/build_native_toolchain_helper.sh --lane 2.14\`
- \`benchmarks/scripts/run_deployed_contract_corpus.sh\`
- \`benchmarks/scripts/build_deployed_contract_source_index.sh\`
- \`benchmarks/scripts/generate_deployed_contract_corpus.sh\`

## Agent-First Surfaces

- diagnostic contract: \`docs/agent/AGENT_DIAGNOSTICS.md\`
- project model strategy: \`docs/PROJECT_MODEL_STRATEGY.md\`
- agent quickstart: \`docs/agent/AGENT_QUICKSTART.md\`
- human quickstart: \`docs/agent/HUMAN_QUICKSTART.md\`
- agent-first architecture direction: \`docs/agent/AGENT_FIRST_COMPILER.md\`
- launch minimum: \`docs/AGENT_FIRST_LAUNCH_MINIMUM_2026-04-24.md\`
- JSON schemas: \`docs/agent/schemas/\`
- command surface docs: \`docs/COMMAND_SURFACE.md\`
- project inspect schema: \`docs/agent/schemas/project-inspect-report.schema.json\`
- agent eval schema: \`docs/agent/schemas/agent-eval-report.schema.json\`
- failure bundle schema: \`docs/agent/schemas/failure-bundle.schema.json\`
- replay report schema: \`docs/agent/schemas/replay-report.schema.json\`
- safe action schema: \`docs/agent/schemas/safe-action-report.schema.json\`
- MCP catalog schema: \`docs/agent/schemas/mcp-catalog.schema.json\`
- deployed-contract source-inventory schema: \`benchmarks/corpora/deployed-contract-source-inventory.schema.json\`
- deployed-contract source-index schema: \`benchmarks/corpora/deployed-contract-source-index.schema.json\`
- deployed-contract corpus schema: \`benchmarks/corpora/deployed-contract-corpus.schema.json\`

## Local Validation Contract

- repo-managed hooks are installed with \`git config core.hooksPath .githooks\`
- \`.githooks/pre-push\` runs \`scripts/local_ci_gate.sh\`
- local validation is authoritative; GitHub Actions are manual-only escape hatches

## Native Toolchain Helpers

- build older helper lanes with \`./scripts/build_native_toolchain_helper.sh --lane 2.14\`
- helper-lane patch experiments use lane metadata \`patch-dir\` and patch files under \`toolchains/cairo-2.14/patches/*.patch\`
- patched helper crates are staged only under \`.uc/helper-lane-patches/\`; use \`UC_HELPER_CARGO_REGISTRY_SRC\` when an alternate Cargo registry source cache is required
- Cairo \`2.14\` frontend trace: set \`UC_CAIRO214_SIZE_TRACE=/abs/path/to/trace.tsv\` on helper runs to collect bounded local TSV counter samples for size-estimation and dummy-Sierra events

## Native Compile Hot Paths

- session image persist/restore: \`native_compile_session_image_path\` in \`crates/uc-cli/src/main.rs\`
- buildinfo persist/restore: \`native_buildinfo_sidecar_path\` in \`crates/uc-cli/src/main.rs\`
- source tracking scan: \`native_scan_tracked_sources\` in \`crates/uc-cli/src/main.rs\`
- session state build: \`build_native_compile_session_state\` in \`crates/uc-cli/src/main.rs\`
- session refresh: \`with_native_compile_session\` in \`crates/uc-cli/src/main.rs\`
- native build entry: \`run_native_build_inner\` in \`crates/uc-cli/src/main.rs\`
- native compiler config: \`native_compiler_config\` in \`crates/uc-cli/src/main.rs\`

## Regression Test Hotspots

- persisted session/buildinfo tests: \`native_compile_session_image_round_trip_restores_tracked_sources_and_dependency_index\` in \`crates/uc-cli/src/main_tests.rs\`
- tracked-source scan tests: \`native_collect_tracked_sources_with_source_root_mtime_matches_individual_scans\` in \`crates/uc-cli/src/main_tests.rs\`

## Local Skills

- \`.claude/skills/uc-pr-review-loop/SKILL.md\`
- \`.claude/skills/uc-native-debug/SKILL.md\`
- \`.claude/skills/uc-benchmark-gate/SKILL.md\`
EOF_MAP

mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
TMP=""
printf 'wrote %s\n' "$OUT"
