#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="${1:-$ROOT/docs/agent/REPO_MAP.md}"
if command -v mktemp >/dev/null 2>&1; then
  TMP="$(mktemp)"
else
  echo "mktemp not found; please install coreutils or provide mktemp in PATH" >&2
  exit 1
fi
trap '[[ -n "${TMP:-}" ]] && rm -f "$TMP"' EXIT

line_of() {
  local pattern="$1"
  local file="$2"
  local line
  line="$({ rg -n "$pattern" "$file" || true; } | head -n 1 | cut -d: -f1)"
  if [[ -n "$line" ]]; then
    printf '%s' "$line"
  else
    printf 'n/a'
  fi
}

MAIN="$ROOT/crates/uc-cli/src/main.rs"
TESTS="$ROOT/crates/uc-cli/src/main_tests.rs"

cat > "$TMP" <<EOF_MAP
# Repo Map

This file is generated by \`scripts/refresh_repo_map.sh\`. Do not edit manually.

## Top-Level Layout

- \`crates/uc-cli\`: CLI, daemon, native compile path, cache/session restore, benchmarks integration.
- \`crates/uc-core\`: artifact and session primitives shared by the CLI.
- \`benchmarks/\`: fixtures, scripts, gates, baselines, and result outputs.
- \`docs/\`: architecture, roadmap, benchmark plan, research, and agent handoff docs.
- \`scripts/\`: bootstrap and validation helpers.
- \`third_party/cairo-lang-filesystem\`: local Cairo filesystem patch surface for keyed invalidation.

## Bootstrap Files

- \`AGENTS.md\`
- \`.codex/START_HERE.md\`
- \`docs/agent/PR_BOT_POLICY.md\`
- \`.coderabbit.yaml\`
- \`.pr_agent.toml\`
- \`best_practices.md\`
- \`pr_compliance_checklist.yaml\`

## Key Commands

- \`make doctor\`
- \`make agent-map\`
- \`make agent-validate\`
- \`make validate-fast\`
- \`make validate-native\`
- \`make benchmark-strict-smoke\`
- \`make benchmark-strict-research\`

## Native Compile Hot Paths

- session image persist/restore: \`crates/uc-cli/src/main.rs:$(line_of '^fn native_compile_session_image_path' "$MAIN")\`
- buildinfo persist/restore: \`crates/uc-cli/src/main.rs:$(line_of '^fn native_buildinfo_sidecar_path' "$MAIN")\`
- source tracking scan: \`crates/uc-cli/src/main.rs:$(line_of '^fn native_scan_tracked_sources' "$MAIN")\`
- session state build: \`crates/uc-cli/src/main.rs:$(line_of '^fn build_native_compile_session_state' "$MAIN")\`
- session refresh: \`crates/uc-cli/src/main.rs:$(line_of '^fn with_native_compile_session' "$MAIN")\`
- native build entry: \`crates/uc-cli/src/main.rs:$(line_of '^fn run_native_build_inner' "$MAIN")\`
- native compiler config: \`crates/uc-cli/src/main.rs:$(line_of '^fn native_compiler_config' "$MAIN")\`

## Regression Test Hotspots

- persisted session/buildinfo tests: \`crates/uc-cli/src/main_tests.rs:$(line_of '^fn native_compile_session_image_round_trip_restores_tracked_sources_and_dependency_index' "$TESTS")\`
- tracked-source scan tests: \`crates/uc-cli/src/main_tests.rs:$(line_of '^fn native_collect_tracked_sources_with_source_root_mtime_matches_individual_scans' "$TESTS")\`

## Local Skills

- \`.claude/skills/uc-pr-review-loop/SKILL.md\`
- \`.claude/skills/uc-native-debug/SKILL.md\`
- \`.claude/skills/uc-benchmark-gate/SKILL.md\`
EOF_MAP

mkdir -p "$(dirname "$OUT")"
mv "$TMP" "$OUT"
TMP=""
printf 'wrote %s\n' "$OUT"
